### ISSUE TITLE
Wrong vendor name/url in plugin build

### ISSUE THREAD

**Issue by neverov-test** [jonnyzzz/TeamCity.GitHub#107]
The plugin claims that the vendor is 'JetBrains, s.r.o.' which is not true. Could you please change it to point to this repository in order to avoid confusion?

**Comment by jonnyzzz** [comment]
Sorry. Thanks for reporting that. I'd be happy to update README.md to better note there is official support in TeamCity. Please do not hesitate to let me know a fix is required or expected
