### ISSUE TITLE
Plugin not accessible at specified location

### ISSUE THREAD

**Issue by mferno** [jonnyzzz/TeamCity.GitHub#108]
Hello

Trying to download the plugin from [here](http://teamcity.jetbrains.com/guestAuth/repository/download/bt398/lastest.lastSuccessful/teamcity.github.zip) responds with a 404 since 12:20 pm.

Thanks
Mathias

**Comment by jonnyzzz** [comment]
It was a dependency change. Fixed it now. Please git it a try
