### ISSUE TITLE
How to allow builds for Trusted PRs for open source projects?

### ISSUE THREAD

**Issue by SimplyAhmazing** [jonnyzzz/TeamCity.GitHub#115]
How can one determine if the PR build is being triggered by a trusted user in Github vs an outside fork when it comes to open source projects?

**Comment by jonnyzzz** [comment]
I do not see an easy solution to that. Do you know if it is at least
possible to implement via GitHub API?

It may play good, if you will set to start PR builds manually on TeamCity,
so that to delegate this decision to users

Best regards,
Eugene Petrenko

**Comment by SimplyAhmazing** [comment]
@jonnyzzz I've been looking into a way to implement this via Github API, haven't quite found a clean way but still hacking at it. Unfortunately I want builds to happen automatically on commit, like 
Travis
