### ISSUE TITLE
Automate deployment of android apk to Google Play Store

### ISSUE THREAD

**Issue by santoshchauhan12** [jonnyzzz/TeamCity.GitHub#116]
Hello Team,

I was looking to automate the depolyment of android apk to google play store via team city.For this i want to feed some script which will accept the parameters like 

- track (aplha, beta, production)
- google play service account
- serviceAccountKeyFile (Pk12 file)
- version code
- version number
- hash salt (if it is production)

and will upload apk to google play store.

Here are some reference i got to do that:
https://github.com/codepath/android_guides/wiki/Automating-Publishing-to-the-Play-Store
https://developers.google.com/android-publisher/getting_started

but i haven't got exact solution to do from team city.
Attaching the screenshot where i need a help for adding a script.![automatescript_to_upload](https://user-images.githubusercontent.com/28190139/36304711-a21c3f88-1336-11e8-85c7-47a4a23cd9fd.png)
Any help will be appreciated

Thanks..

**Comment by VladRassokhin** [comment]
How it's related to 'third-party' TeamCity plugin? Please [create issue in YouTrack](https://youtrack.jetbrains.com/issues/TW) or open [forum thread](https://teamcity-support.jetbrains.com/hc/en-us/community/topics) so someone from TeamCity team will answer there.

**Comment by santoshchauhan12** [comment]
@VladRassokhin 

We have already  created the ticket for this issue here: https://youtrack.jetbrains.com/issue/TW-53793
Waiting  for reply from TeamCity.

Could you please suggest me either script or plugin regarding this issue.
Thanks
