### ISSUE TITLE
Pull request status banners

### ISSUE THREAD

**Issue by sommestad** [jonnyzzz/TeamCity.GitHub#46]
It would be great to have TravisCI/etc-style status updates to the GitHub Pull requests, i.e. a prominent banner with the state instead of using comments.

Should be able to hook up in to the [Status API](https://github.com/blog/1227-commit-status-api).

**Comment by Cryptophobia** [comment]
Hi,
How did you create this custom status? Did you create your own GitHub status API wrapper or did you use this TeamCity.GitHub integration?
