### ISSUE TITLE
Does not work at Teamcity 9.0

### ISSUE THREAD

**Issue by jmaxxz** [jonnyzzz/TeamCity.GitHub#74]
I've uploaded the plugin, but it does not appear in the list of installed plugins.

**Comment by jonnyzzz** [comment]
Please check you have you uploaded. The .zip could be sources, not binaries, or the .zip may be corrupted

**Comment by jmaxxz** [comment]
Yes, I uploaded the built version. TC extracted it to TeamCity\plugins\.unpacked\teamcity.github\server and I see 7 jars

**Comment by jonnyzzz** [comment]
Please restart server and check what is in logs. There could be a error shown

**Comment by jmaxxz** [comment]
I must have done something wrong last time. After reboot the plugin booted right up without issue. Closing this issue.

**Comment by jmaxxz** [comment]
Which log file should I be looking in to debug issues if my pull requests are not being updated with the build data?

**Comment by jonnyzzz** [comment]
Check teamcity-server.log
