### ISSUE TITLE
Report tests as failed, not errored, when the build completes but tests have failed

### ISSUE THREAD

**Issue by paradox460** [jonnyzzz/TeamCity.GitHub#77]
When a test has failed, it should be marked as such. Currently, tests are marked as  `errored`, even when they complete their build.

Errored should only happen if no test data is available for report, i.e. a build step reports something like `Exit Code: 1`

**Comment by jonnyzzz** [comment]
In general this may not be possible to tell test failure from the build failure. Of course this works for some java test-runner cases. Anyway it requires users to carefully setup their builds to achieve it
