### ISSUE TITLE
Two factor auth

### ISSUE THREAD

**Issue by balauru** [jonnyzzz/TeamCity.GitHub#80]
Any idea on how can I make this work with 2 factor authorization?

**Comment by jonnyzzz** [comment]
I think you can 2-factor login to github, next you may create an access
token there and next you use the token on the plugin build feature settings
. It's not clear to me how we can handle it in the other way without
registering TeamCity server instance as application on github. Could you
please elaborate what you mean

**Comment by balauru** [comment]
It makes sens to register teamcity on github.

But I am not sure how I can use the token with the plugin? I only see a username and passwords field.

**Comment by jonnyzzz** [comment]
Currently you may use GitHub access token from the plugin settings UI. All you need is to open the build feature settings and follow the link/instructions. The token can be generated on GitHub from https://github.com/settings/tokens

If you have time, you may consider providing patch for supporting things via github application

**Comment by balauru** [comment]
Thanks for the reply.

Unfortunately I have no idea what you mean by `the plugin settings UI`, can you tell me where this screen is, I only a `username` and `password` fields in the plugin UI

![selection_047](https://cloud.githubusercontent.com/assets/679198/7912715/9342646e-0872-11e5-9f02-82a8837df238.png)

**Comment by jonnyzzz** [comment]
It looks like you use too old version of the plugin. Please upgrade.

**Comment by balauru** [comment]
Ah, the update did the trick, thanks.
