### ISSUE TITLE
Installed Plugin, Not Showing in Build Features

### ISSUE THREAD

**Issue by ajcurtin** [jonnyzzz/TeamCity.GitHub#84]
Hi,

I am using teamcity 9.x.x and have added the plugin to the plugin folder and restarted teamcity. The plugin doesn't show a version number or developer in the admin ui on team city and also, when I select a build project and "add build feature" the "send results to github" feature is not an option.

Can you help?

**Comment by superdale** [comment]
I dropped it into the follow folder and restarted the server and it showed up. /teamcity/.BuildServer/plugins/. From what I have been hearing you will need to make sure you have the latest version of the plugin.

**Comment by jonnyzzz** [comment]
You should see the version if the plugin on Administration / Plugins List
page

If you do not see plugin there, please check you downloaded the right zip
and it is not corrupted

**Comment by ajcurtin** [comment]
I got that working, thanks for your help. Now, when trying to post the status to github I am seeing these errors in teamcity-server.log. Can you help me identify where I've configured the build feature incorrectly?

I don't know what to enter in the configuration fields to get this to work properly, as I did enter the repo name, owner username and correct password etc.

WARN - .github.api.impl.GitHubApiImpl - Failed to complete query to GitHub with:
  requestURL: https://api.github.com/repos/talliedev/Tallie/statuses/commithashwashere
  requestMethod: POST
  requestEntity: {"state":"pending","target_url":"myteamcityserver.com"
buildId\u003d164871\u0026buildTypeId\u003dbt108","description":"Started TeamCity Build SpringAhead Branch :: SpringTime server","context":"continuous-integration/teamcity"}
  response: HTTP/1.1 404 Not Found
  responseEntity: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"} 
[2015-06-20 23:17:28,969]   WARN - lty.github.ChangeStatusUpdater - Failed to update GitHub status for hash: deleted, buildId: 164871, status: Pending. Failed to complete request to GitHub. Status: HTTP/1.1 404 Not Found 
java.io.IOException: Failed to complete request to GitHub. Status: HTTP/1.1 404 Not Found

**Comment by ajcurtin** [comment]
I got the 404 fixed, but now the plugin is commenting on each team city projects completed build instead of the root pull request "73" or whatever its number is. So, lets say I request pull req #72 which in turn triggers a bunch of project builds of "database, web, cloud". It is commenting on the commits that made changes to "database,web,cloud" that were successful but not to the root pull request #72 in github. Any ideas?

**Comment by ajcurtin** [comment]
Fixed and mentioned in #83
