### ISSUE TITLE
Improve support for multiple builds against one repository

### ISSUE THREAD

**Issue by shackpank** [jonnyzzz/TeamCity.GitHub#86]
I've recently tried to break up a build on teamcity into 2 steps communicating state back to github with this plugin. The status updates for the second build end up overwriting the ones supplied by the first one.

It looks like using a different [context](https://developer.github.com/v3/repos/statuses/) for each build type when updating the commit status will achieve this, and it can be done by changing [this line](https://github.com/jonnyzzz/TeamCity.GitHub/blob/master/server/src/jetbrains/teamcilty/github/ui/UpdateChangeStatusFeature.java#L127) or the code that calls it - but that's about as far as I've got.

**Comment by griwes** [comment]
There's a field called "Context" in Build Feature configuration that does this.

**Comment by shackpank** [comment]
I see! Awesome, thank you @griwes exactly what I needed.
