### ISSUE TITLE
Status check issue since github ui update?

### ISSUE THREAD

**Issue by omares** [jonnyzzz/TeamCity.GitHub#87]
Since github updated their pull request ui we are experiencing the issue that only one status check gets shown instead of all check that have been run. It seems the last status overwrites the previous one.

I am not 100% sure if it is related to the change github made, or if that issue was already existing before that.

Are we the only ones experiencing this issue? Does it maybe have something todo with the fact that all reported checks use "default" as name? Is there a way to change that name from configuration side?

**Comment by griwes** [comment]
I guess this is a duplicate of #86, so basically "please do read all configuration options before asking"?

**Comment by omares** [comment]
Bah, sorry you are right.
