### ISSUE TITLE
Multiple build statuses for the same commit overwrite one another

### ISSUE THREAD

**Issue by mattgibson** [jonnyzzz/TeamCity.GitHub#88]
I have set up some build configurations where a plugin I have written is tested agains several different configurations of its host system. This results in several commit status updates to Github. However, if one of the earlier statuses is a fail and one of the later statuses is a pass, then the pass overwrites the fail and the pull request looks OK, even though it should not. 

I think the solution is to vary the context string that is sent with the status update. I think this is the same all the time at the moment, so if it was changed to include the build configuration id, then hopefully, the statuses would be separate, as in the case of other systems reporting to pull request separately (e.g. here: https://github.com/resque/resque-web/pull/93 - click on 'view details' next to the merge commit message to see that there are multiple status updates)

By using the build configuration id, a build that errored due to a config problem can be repeated and will correctly overwrite the mistake, but a different configuration for a different host system will not.

My Java skills are non-existent, so I'm not really in a position to make a pull request. Sorry!

**Comment by griwes** [comment]
Seriously?

#86, #87.

Literally the two previously closed tickets, which is even worse than the unability to read configuration options in the build feature some people seem to have developed.

**Comment by mattgibson** [comment]
D'oh! Many apologies. 

In my defence I think I have an older version of the code without realising it, as the context field was not there for me when I checked. I also read the source code to try to find how to context was set before concluding it was always fixed. That'll teach me to assume I can read Java!

Closing.
