### ISSUE TITLE
Add config option to change status description

### ISSUE THREAD

**Issue by ruudk** [jonnyzzz/TeamCity.GitHub#98]
The default status description is: 

```
scheduleChangeUpdate(version, build, "Started TeamCity Build " + build.getFullName(), GitHubChangeState.Pending);
```

It would be really awesome if we could change that to something we want. For example, the current build step that's being executed.

**Comment by Cryptophobia** [comment]
:+1:  @ruudk This would be a really nice feature as it will allow us to let our developers know which step the build is failing at directly in the StatusAPI message once failed without flooding the PR with comments.
